
modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Stereowalker/Survive/issues"
logoFile="logo.png"
[[mods]]
modId="survive"
version="${file.jarVersion}"
displayName="Survive"
updateJSONURL="https://raw.githubusercontent.com/Stereowalker/My-Home-Page/main/update_files/survive.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/survive"
credits="I'd like to thank all my supporters on Patreon for giving me a reason to continue modding, ChainmailPickaxe for the nice textures, and you for downloading and playing with this mod"
authors="Stereowalker"
description='''
Adds new survival mechanics like thirst, body temperature, sleep management and stamina
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.survive]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.survive]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.survive]]
    modId="unionlib"
    mandatory=true
    versionRange="[7.2.0,7.3.0)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.survive]]
    modId="combat"
    mandatory=false
    versionRange="[1.18.2-9.0.0-beta,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.survive]]
    modId="sereneseasons"
    mandatory=false
    versionRange="[1.18.2-7.0.0.13,)"
    ordering="NONE"
    side="BOTH"
	

